# Generated by Django 2.2.8 on 2020-01-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_verification',
            name='image',
            field=models.ImageField(upload_to='forged_signs/'),
        ),
    ]
