# Generated by Django 2.2.8 on 2020-01-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200109_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_verification_genuine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='genuine_signs/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Sign_verification',
            new_name='Sign_verification_forged',
        ),
    ]
