# Generated by Django 2.2.8 on 2019-12-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_seg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='pdf',
            field=models.ImageField(upload_to='waste/'),
        ),
    ]
