# Generated by Django 2.2.8 on 2019-12-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_seg', '0002_auto_20191231_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waste',
            old_name='pdf',
            new_name='image',
        ),
    ]
