# Generated by Django 2.2.8 on 2020-01-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_seg', '0004_waste_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste_dataset',
            name='actual_category',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='waste_dataset',
            name='image',
            field=models.ImageField(upload_to='wastes/'),
        ),
        migrations.AlterField(
            model_name='waste_dataset',
            name='predicted_category',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
