# Generated by Django 2.2.8 on 2020-01-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_seg', '0005_auto_20200110_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Waste',
        ),
        migrations.AlterField(
            model_name='waste_dataset',
            name='image',
            field=models.ImageField(upload_to='waste/'),
        ),
    ]
