# Generated by Django 2.2.8 on 2020-01-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_seg', '0006_auto_20200110_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste_dataset',
            name='actual_category',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='waste_dataset',
            name='predicted_category',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
